sudo: required
language: "android"

cache: yarn

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10

before_install:
  - "nvm install 7"
  - "node --version"
  - "npm install -g yarn"
  - "openssl aes-256-cbc -d -a -in secrets.tar.enc -out secrets.tar -k thisisveryhard"
  - "tar xvf secrets.tar"

install:
  - "yarn install"

script:
  - "yarn lint:summary || true"
  - "yarn test"
  - "yarn build:android"

deploy:
  - provider: script
    script: "./deploy.sh"
    skip_cleanup: true
    on:
      all_branches: true