sudo: required
language: "android"

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10

before_install:
  - "nvm install 7"
  - "node --version"
  - "npm install -g yarn"

install:
  - "yarn install"

script:
  - "yarn lint:summary || true"
  - "yarn test"
  - "yarn build:android"

deploy:
  - provider: script
    script: "./deploy.sh"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true